---
abstract: 'sugar for MooseX::RelatedClasses'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::RelatedClasses::Aliased
name: MooseX-RelatedClasses-Aliased
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Devel::Caller: 2.00
  Hook::AfterRuntime: 0
  List::MoreUtils: 0
  Moose::Util: 2.00
  MooseX::RelatedClasses: 0.001
  Scalar::Util: 0
  Sub::Install: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-RelatedClasses-Aliased
  homepage: https://metacpan.org/release/MooseX-RelatedClasses-Aliased
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-relatedclasses-aliased
version: 0.001
